<a href="https://colab.research.google.com/github/bahawal-khan/DeepLearning-practice/blob/main/RNN/RNN_Architecture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN

In [2]:
model = Sequential()
model.add(SimpleRNN(3,input_shape= (4,5)))
model.add(Dense(1,activation = 'sigmoid'))
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [3]:
print(model.get_weights()[0].shape)
print(model.get_weights()[0])

(5, 3)
[[ 0.33753294  0.72798854 -0.5378596 ]
 [-0.10184479  0.5031813   0.751995  ]
 [-0.7587852  -0.40212464 -0.57601094]
 [ 0.73099095  0.5584083  -0.622599  ]
 [-0.7426895   0.28914768 -0.70294464]]


In [4]:
print(model.get_weights()[1].shape)
print(model.get_weights()[1])

(3, 3)
[[-0.58137846  0.6901024   0.4309961 ]
 [-0.66951257 -0.10476097 -0.7353761 ]
 [-0.46233332 -0.7160891   0.5229381 ]]


In [5]:
print(model.get_weights()[2].shape)
print(model.get_weights()[2])

(3,)
[0. 0. 0.]


In [6]:
print(model.get_weights()[3].shape)
print(model.get_weights()[3])

(3, 1)
[[ 1.0131747]
 [ 1.2057542]
 [-0.8582413]]


In [8]:
print(model.get_weights()[4].shape)
print(model.get_weights()[4])

(1,)
[0.]


**Convert the text in to vector Integer encodig**

In [3]:
import numpy as np

In [4]:
docs = [
    "Artificial intelligence is transforming modern healthcare by improving disease diagnosis.",
    "Machine learning algorithms learn patterns from data to make accurate predictions.",
    "Deep learning models use multiple neural network layers to solve complex problems.",
    "Natural language processing helps computers understand and generate human language.",
    "Data scientists clean and preprocess data before training machine learning models.",
    "Recurrent neural networks are designed to process sequential data like text and speech.",
    "Transformers have replaced recurrent neural networks in most modern language models.",
    "Large language models can answer questions, summarize documents, and generate code.",
    "Good quality data usually leads to better machine learning performance.",
    "Artificial intelligence is becoming an essential skill for future software engineers."
]

In [6]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token="<OOV>")

In [7]:
tokenizer.fit_on_texts(docs)

In [8]:
tokenizer.word_index

{'<OOV>': 1,
 'data': 2,
 'learning': 3,
 'to': 4,
 'models': 5,
 'language': 6,
 'and': 7,
 'machine': 8,
 'neural': 9,
 'artificial': 10,
 'intelligence': 11,
 'is': 12,
 'modern': 13,
 'generate': 14,
 'recurrent': 15,
 'networks': 16,
 'transforming': 17,
 'healthcare': 18,
 'by': 19,
 'improving': 20,
 'disease': 21,
 'diagnosis': 22,
 'algorithms': 23,
 'learn': 24,
 'patterns': 25,
 'from': 26,
 'make': 27,
 'accurate': 28,
 'predictions': 29,
 'deep': 30,
 'use': 31,
 'multiple': 32,
 'network': 33,
 'layers': 34,
 'solve': 35,
 'complex': 36,
 'problems': 37,
 'natural': 38,
 'processing': 39,
 'helps': 40,
 'computers': 41,
 'understand': 42,
 'human': 43,
 'scientists': 44,
 'clean': 45,
 'preprocess': 46,
 'before': 47,
 'training': 48,
 'are': 49,
 'designed': 50,
 'process': 51,
 'sequential': 52,
 'like': 53,
 'text': 54,
 'speech': 55,
 'transformers': 56,
 'have': 57,
 'replaced': 58,
 'in': 59,
 'most': 60,
 'large': 61,
 'can': 62,
 'answer': 63,
 'questions': 64,
 '

In [9]:
tokenizer.word_counts

OrderedDict([('artificial', 2),
             ('intelligence', 2),
             ('is', 2),
             ('transforming', 1),
             ('modern', 2),
             ('healthcare', 1),
             ('by', 1),
             ('improving', 1),
             ('disease', 1),
             ('diagnosis', 1),
             ('machine', 3),
             ('learning', 4),
             ('algorithms', 1),
             ('learn', 1),
             ('patterns', 1),
             ('from', 1),
             ('data', 5),
             ('to', 4),
             ('make', 1),
             ('accurate', 1),
             ('predictions', 1),
             ('deep', 1),
             ('models', 4),
             ('use', 1),
             ('multiple', 1),
             ('neural', 3),
             ('network', 1),
             ('layers', 1),
             ('solve', 1),
             ('complex', 1),
             ('problems', 1),
             ('natural', 1),
             ('language', 4),
             ('processing', 1),
             ('he

In [10]:
sequence = tokenizer.texts_to_sequences(docs)
sequence

[[10, 11, 12, 17, 13, 18, 19, 20, 21, 22],
 [8, 3, 23, 24, 25, 26, 2, 4, 27, 28, 29],
 [30, 3, 5, 31, 32, 9, 33, 34, 4, 35, 36, 37],
 [38, 6, 39, 40, 41, 42, 7, 14, 43, 6],
 [2, 44, 45, 7, 46, 2, 47, 48, 8, 3, 5],
 [15, 9, 16, 49, 50, 4, 51, 52, 2, 53, 54, 7, 55],
 [56, 57, 58, 15, 9, 16, 59, 60, 13, 6, 5],
 [61, 6, 5, 62, 63, 64, 65, 66, 7, 14, 67],
 [68, 69, 2, 70, 71, 4, 72, 8, 3, 73],
 [10, 11, 12, 74, 75, 76, 77, 78, 79, 80, 81]]

***Now Apply padding to make Vectors of same size.***

In [11]:
from keras.utils import pad_sequences

sequences = pad_sequences(sequence,padding = 'post')
sequences

array([[10, 11, 12, 17, 13, 18, 19, 20, 21, 22,  0,  0,  0],
       [ 8,  3, 23, 24, 25, 26,  2,  4, 27, 28, 29,  0,  0],
       [30,  3,  5, 31, 32,  9, 33, 34,  4, 35, 36, 37,  0],
       [38,  6, 39, 40, 41, 42,  7, 14, 43,  6,  0,  0,  0],
       [ 2, 44, 45,  7, 46,  2, 47, 48,  8,  3,  5,  0,  0],
       [15,  9, 16, 49, 50,  4, 51, 52,  2, 53, 54,  7, 55],
       [56, 57, 58, 15,  9, 16, 59, 60, 13,  6,  5,  0,  0],
       [61,  6,  5, 62, 63, 64, 65, 66,  7, 14, 67,  0,  0],
       [68, 69,  2, 70, 71,  4, 72,  8,  3, 73,  0,  0,  0],
       [10, 11, 12, 74, 75, 76, 77, 78, 79, 80, 81,  0,  0]], dtype=int32)

**Now work on the imdb Dataset**

In [13]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,Flatten,SimpleRNN

In [14]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [15]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [16]:
X_train.shape

(25000,)

In [17]:
X_test.shape

(25000,)

In [18]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [20]:
len(X_train[0])

218

In [21]:
len(X_train[10])

450

**Make all to an equal length and apply pad_sequence**

In [25]:
from keras.utils import pad_sequences

In [26]:
X_train = pad_sequences(X_train,padding = 'post')
X_test =  pad_sequences(X_test,padding = 'post')

In [27]:
len(X_train[0])

2494

In [28]:
len(X_train[10])

2494

In [29]:
X_train[0]

array([ 1, 14, 22, ...,  0,  0,  0], dtype=int32)

In [31]:
X_train.shape

(25000, 2494)

In [44]:
model1 = Sequential()

In [45]:
model1.add(SimpleRNN(32,input_shape = (2494,1),return_sequences = False))
model1.add(Dense(1,activation = 'sigmoid'))

model1.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_9 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [49]:
model1.compile(loss = 'binary_crossentropy',optimizer='adam',metrics = ['accuracy'])


In [50]:
model1.fit(X_train,y_train,epochs = 5,validation_data = (X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 113s 141ms/step - accuracy: 0.5039 - loss: 0.6939 - val_accuracy: 0.4991 - val_loss: 0.6936
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 106s 135ms/step - accuracy: 0.4992 - loss: 0.6953 - val_accuracy: 0.5027 - val_loss: 0.6966
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 106s 135ms/step - accuracy: 0.4978 - loss: 0.6945 - val_accuracy: 0.5010 - val_loss: 0.6935
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 106s 136ms/step - accuracy: 0.4984 - loss: 0.6946 - val_accuracy: 0.4978 - val_loss: 0.6945
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 105s 135ms/step - accuracy: 0.4938 - loss: 0.6946 - val_accuracy: 0.4992 - val_loss: 0.6936


**Embedding Technique**

In [9]:
docs_emb = [
    "Artificial intelligence is transforming modern healthcare by improving disease diagnosis.",
    "Machine learning algorithms learn patterns from data to make accurate predictions.",
    "Deep learning models use multiple neural network layers to solve complex problems.",
    "Natural language processing helps computers understand and generate human language.",
    "Data scientists clean and preprocess data before training machine learning models.",
    "Recurrent neural networks are designed to process sequential data like text and speech.",
    "Transformers have replaced recurrent neural networks in most modern language models.",
    "Large language models can answer questions, summarize documents, and generate code.",
    "Good quality data usually leads to better machine learning performance.",
    "Artificial intelligence is becoming an essential skill for future software engineers."
]

In [10]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer1 = Tokenizer()

In [11]:
tokenizer1.fit_on_texts(docs_emb)

In [12]:
len(tokenizer1.word_counts)

80

In [13]:
seq = tokenizer1.texts_to_sequences(docs_emb)
seq

[[9, 10, 11, 16, 12, 17, 18, 19, 20, 21],
 [7, 2, 22, 23, 24, 25, 1, 3, 26, 27, 28],
 [29, 2, 4, 30, 31, 8, 32, 33, 3, 34, 35, 36],
 [37, 5, 38, 39, 40, 41, 6, 13, 42, 5],
 [1, 43, 44, 6, 45, 1, 46, 47, 7, 2, 4],
 [14, 8, 15, 48, 49, 3, 50, 51, 1, 52, 53, 6, 54],
 [55, 56, 57, 14, 8, 15, 58, 59, 12, 5, 4],
 [60, 5, 4, 61, 62, 63, 64, 65, 6, 13, 66],
 [67, 68, 1, 69, 70, 3, 71, 7, 2, 72],
 [9, 10, 11, 73, 74, 75, 76, 77, 78, 79, 80]]

In [14]:
from keras.utils import pad_sequences
seqs = pad_sequences(seq,padding = 'post')

In [15]:
seqs

array([[ 9, 10, 11, 16, 12, 17, 18, 19, 20, 21,  0,  0,  0],
       [ 7,  2, 22, 23, 24, 25,  1,  3, 26, 27, 28,  0,  0],
       [29,  2,  4, 30, 31,  8, 32, 33,  3, 34, 35, 36,  0],
       [37,  5, 38, 39, 40, 41,  6, 13, 42,  5,  0,  0,  0],
       [ 1, 43, 44,  6, 45,  1, 46, 47,  7,  2,  4,  0,  0],
       [14,  8, 15, 48, 49,  3, 50, 51,  1, 52, 53,  6, 54],
       [55, 56, 57, 14,  8, 15, 58, 59, 12,  5,  4,  0,  0],
       [60,  5,  4, 61, 62, 63, 64, 65,  6, 13, 66,  0,  0],
       [67, 68,  1, 69, 70,  3, 71,  7,  2, 72,  0,  0,  0],
       [ 9, 10, 11, 73, 74, 75, 76, 77, 78, 79, 80,  0,  0]], dtype=int32)

In [16]:
from tensorflow.keras.layers import Embedding

In [17]:
from tensorflow.keras.models import Sequential

In [24]:
model2 = Sequential()
model2.add(Embedding(input_dim=81, output_dim=5))
model2.build(input_shape=(None, 13))

model2.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 13, 5)          │           405 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 405 (1.58 KB)

 Trainable params: 405 (1.58 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
pred = model2.predict(seqs)
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step


array([[[-1.24362819e-02, -4.51899692e-03,  4.20442484e-02,
          2.85063125e-02, -4.37410474e-02],
        [ 3.32670696e-02,  3.95579264e-03, -4.70249727e-03,
          1.07541196e-02, -1.71423927e-02],
        [ 4.64622416e-02,  3.07258219e-03,  6.16436079e-03,
          2.00144313e-02,  1.73230097e-03],
        [ 9.91983339e-03,  3.54694985e-02,  2.61940621e-02,
          2.62043625e-03, -4.72361557e-02],
        [ 2.02800520e-02, -1.05147138e-02, -3.62565890e-02,
          4.52924408e-02,  5.66947460e-03],
        [ 2.80358531e-02,  4.68826778e-02,  3.56222279e-02,
          2.81891264e-02,  1.96421482e-02],
        [-1.39123574e-02, -4.82411385e-02, -4.83330972e-02,
          7.30524212e-03,  2.97564529e-02],
        [ 1.17567927e-03, -3.30290943e-02, -2.71043926e-03,
          6.65075704e-03,  1.19412318e-02],
        [-7.88491964e-03,  2.95497067e-02, -1.60083398e-02,
          2.72082351e-02, -2.96432264e-02],
        [-1.10457055e-02, -5.38706779e-03,  2.29044817e-02,
    

In [27]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import SimpleRNN,Dense,Flatten,Embedding

In [28]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [30]:
x_train = pad_sequences(X_train,padding = 'post',maxlen = 50)
x_test = pad_sequences(X_test,padding = 'post',maxlen = 50)

In [31]:
x_train.shape

(25000, 50)

In [42]:
from tensorflow.keras.layers import Input

model = Sequential([
    Input(shape=(2494,)),
    Embedding(input_dim=10000, output_dim=2),
    SimpleRNN(32),
    Dense(1, activation='sigmoid')
])

model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)        │ (None, 2494, 2)        │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_3 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [43]:
model.compile(loss = 'binary_crossentropy',optimizer='adam',metrics = ['accuracy'])

**I cannot run because GPU is not working. It takes too much time in CPU.**

In [ ]:
model.fit(x_train,y_train,epochs = 5,validation_data = (x_test,y_test))